### ISSUE TITLE
Refactor APIs

### ISSUE THREAD

**Issue by whitlockjc** [30x/kiln#74]
We recently discussed shipyardctl and how it maps not only to Apigee but also within the ecosystem of other Apigee CLIs. Here is the latest design document: https://docs.google.com/document/d/1yZSSrH1kIwxT5VNwkB6HQxTpY90VjwLAlcPj7P42xj8/edit  Based on this, we need to refactor the APIs to better match the terminology we'll be using.  Here are the changes:

* Change the `imagespaces` path segment to `appspaces`
* Change the `images` path segment to `apps`
* Change the `revision` parameter to be optional, is part of the `name` parameter now and handled as described in https://github.com/30x/shipyardctl/issues/51
* Change the `nodeRevision` parameter to be known as `runtime` and handled as described in https://github.com/30x/shipyardctl/issues/51 _(Make sure that only `node` is allowed for the first portion of the `runtime` pattern)_

**Comment by whitlockjc** [comment]
We should revisit this before implementing.

**Comment by whitlockjc** [comment]
I think we've got a URI consistency issue.  Right now, `enrober` scopes deployments at the _environment_ level and its URIs are formatted accordingly: `/environments/{org:env}/...`  `kiln`, on the other hand, scopes applications/images to the _organization_ level but its URIs are not formatted accordingly: `/imagespaces/{org}/images/...`  Does it make sense to have more consistent URIs, possibly something like `/organizations/{org}/images/...` or `/orgs/{org}/images/...`

**Note:** `images` will become `apps` as part of this refactoring regardless of the URI pattern scoping issue above.

cc @mpnally

**Comment by mpnally** [comment]
We could do that — it would probably make the Edge folks happy. If you want to highlight Kubernetes and Docker, it makes sense to keep things the way we have them, because it matches the underlying K8S and Docker data organization and so leverages what knowledgeable people know about those systems. However, It is probably more in the spirit of Edge alignment to change it. The current Edge approach to this is "creative". You deploy going a POST to: /v1/o/{org_name}/environments/{env-name}/apis/{api_name}/revisions/{revision_number}/deployments
However you list deployments by doing a GET on: /v1/o/{org_name}/environments/test/deployments.

**Comment by whitlockjc** [comment]
@jbowen93 and @noahdietz, give ^^^ a read and let's talk on Monday about the Shipyard URIs.
